# Generated by Django 4.1.2 on 2022-10-24 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^010-?[1-9]\\d{3}-?\\d{4}$"
                    )
                ],
            ),
        ),
    ]
